version: "2"
services:
  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - postgres
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: P@ssword123
    ports:
      - "5432:5432"